### ISSUE TITLE
Third GEDI tutorial

### ISSUE THREAD

**Issue by boswellp** [ornldaac/gedi_tutorials#1]
In GEDI Level 4 documentation or guidance, I saw a link to a third GEDI Level 4 tutorial that dealt with "exploration" of Level 4 data. Will this tutorial be available shortly?

**Comment by rupesh2** [comment]
Hi @boswellp , we will release the third tutorial this week. We will keep you posted.

**Comment by rupesh2** [comment]
@boswellp the third tutorial is available here: https://github.com/ornldaac/gedi_tutorials/blob/main/3_gedi_l4a_exploring_data.ipynb. Let us know if you see any issues.
