### ISSUE TITLE
polygons/harvard.json is missing

### ISSUE THREAD

**Issue by jpswinski** [ornldaac/gedi_tutorials#10]
The tutorial "gedi_l4a_direct_s3_access.ipynb" no longer runs because the harvard.json file is not in the polygons folder.

**Comment by rupesh2** [comment]
Hi @jpswinski, Thank you for letting us know about the missing json file. We have now added it to the folder.

**Comment by jpswinski** [comment]
@rupesh2 Thanks for the quick response!  I did a pull and saw the file.
