### ISSUE TITLE
Package Versions for Turorials

### ISSUE THREAD

**Issue by Yanhao29** [ornldaac/gedi_tutorials#11]
Hi,

First thank you so much for the tutorials and notebooks. They are really clear and helpful.
I was running 3_gedi_l4a_exploring_data.ipynb, which is good until 
```
mt_leuser_3857_gdf = mt_leuser_gdf.to_crs(epsg=3857)
```
where an error is encountered (**ProjError: x, y, z, and time must be same size**). 
I have tried using different versions of **pyproj** and **proj**, but still couldn't solve the problem.
Since there are many dependencies with the packages used in the tutorial, would it be possible for you to provide the package versions that you are using?

Thank you very much!

**Comment by rupesh2** [comment]
Hi @Yanhao29 , Thank you for contacting us! We have now added [requirements.txt](https://github.com/ornldaac/gedi_tutorials/blob/main/requirements.txt) to the github and updated the [notebook](https://github.com/ornldaac/gedi_tutorials/blob/main/3_gedi_l4a_exploring_data.ipynb) to reflect the dependencies. Let us know if you are still seeing the errors.
