### ISSUE TITLE
Two questions about the tutorial

### ISSUE THREAD

**Issue by sbanchero** [ornldaac/gedi_tutorials#3]
Hi!
I've two questions about the tutorial and the AGBD calculation.

1) The document [1] and [2] specify that par[1] is always the intercept term but in the tutorial [3_gedi_l4a_exploring_data.ipynb](https://github.com/ornldaac/gedi_tutorials/blob/main/3_gedi_l4a_exploring_data.ipynb) say: _The variable par gives model coefficients - the first element of the list is always the slope of the linear model._ Which is the correct one? 

![image](https://user-images.githubusercontent.com/159865/137781399-6a920098-cd40-4f26-a6fb-22fac40e1373.png)

2) Also, I have another question regarding the use of the existing model in ANCILLARY / model_data. For example, in the DBT_NAm case if the vertors are: 
predictor_id: [1 2 0 0 0 0 0 0]
rh_index: [50 98  0  0  0  0  0  0]
par: [-120.77709198    5.50771856    6.80801821    0.            0.        ]

How use the information to make the model equation? The vectors index starts from 0 or 1?

Follow both [1] or [2] is some confusing the order of the parameters because I don't understand how I should combine the rh values as only have two values 1 and 2 within the prediction_id for rh50 and rh98 respectively but tree par coefficients. 

I understand that a possible way can be: 
AGBD = -120.77709198 + 5.50771856 * rh50 + 6.80801821 * rh98^2

Is this correct?

I hope my explanation has been understood.

Thank you very much for the tutorials. 
Best regards
Santiago 

[1] https://daac.ornl.gov/daacdata/gedi/GEDI_L4A_AGB_Density/comp/GEDI_L4A_Common_Queries.pdf
[2] https://daac.ornl.gov/GEDI/guides/GEDI_L4A_AGB_Density.html

**Comment by rupesh2** [comment]
HI @sbanchero , 1) `par[1]` should be the "intercept"; it is now updated in the tutorial description. 2) The equation for DBT_NAm should be `AGBD = -120.77709197998047 + 5.507718563079834 x RH_50 + 6.808018207550049 x RH_98`. `predictor_id` provides here mapping between `rh_index` and `par`. Also, note that both predictor and response variables, in this case, are transformed (`sqrt`).

**Comment by sbanchero** [comment]
Hi @rupesh2 ,
Thank you very much for your answer
