### ISSUE TITLE
Feed word or doi value

### ISSUE THREAD

**Issue by jaimebayes** [ornldaac/gedi_tutorials#4]
Hi folks, 

I was running your 3 notebooks, and they hook me, sadly I could not try it on my interest area, throwing an error related with word **feed**. I was thinking its cause could be that I use geojson instead of json file. Also, I though it could be related with doi value, maybe it just work for your area. Do you know if I can get a doi value for my area? if so, where can I get it?

`doi = '10.3334/ORNLDAAC/1907'# GEDI L4A DOI `
`# CMR API base url`
`cmrurl='https://cmr.earthdata.nasa.gov/search/' `
`doisearch = cmrurl + 'collections.json?doi=' + doi `
`concept_id = requests.get(doisearch).json()['feed']['entry'][0]['id'] `
`print(concept_id) `
``
Any advice will be appreciated.
Thanks in advance, JL

**Comment by rupesh2** [comment]
Hi @jaimebayes, The DOI (Digital Object Identifier) is assigned for the whole dataset. The snippet you shared above will print the `concept_id` for GEDI L4A Version 1 - NASA's unique identifier for this dataset. If you want to search the GEDI L4A files within your area of interest, this tutorial outlines the steps: [2. Searching for a polygonal area of interest (Option 2)](https://github.com/ornldaac/gedi_tutorials/blob/main/1_gedi_l4a_search_download.ipynb). Let us know if you are still seeing the errors. If you can share the geojson file you are using, we can help you troubleshoot.
