### ISSUE TITLE
AGBD linear models

### ISSUE THREAD

**Issue by smita2021** [ornldaac/gedi_tutorials#6]
Is the Table 3. AGBD Linear Models by Prediction Stratum provided in the tutorial https://github.com/ornldaac/gedi_tutorials/blob/main/3_gedi_l4a_exploring_data.ipynb 
is the correct linear models used by GEDI to predict AGBD for all regions and PFT for every shot. If it is yes, than I found since they have with negative values in the model which makes most of the biomass calculation in negative values. For example, I tried with one shot with Rh values provided by L2a and use the model equation for that shot with DBT plant functional type but it comes in negative value. But for that shot predicted AGBD provided by L4A data is with different positive values.
Additionally, using RH values in the model equation gives directly the AGBD in mg/ha?  
Please, provide me the information as I am doing study on comparing GEDI AGBD for North Asia region.

**Comment by rupesh2** [comment]
Hi @smita2021,  Thank you for contacting us. These linear models should be applied in the transformed space, and back-transformed to retrieve AGBD in mg ha-1. We have added a tutorial that shows how to correctly reproduce L4A AGBD estimates from L2A metrics: https://github.com/ornldaac/gedi_tutorials/blob/main/reconstruct_L4A_AGBD_L2A_metrics.ipynb. Hope this helps!

**Comment by smita2021** [comment]
Thank you for providing detail about reproducing AGBD estimates. I also wanted to get clear if we want to use GEDI model for field biomass calculation, then can we use the model equation? As I took GEDI footprint for fieldwork and have terrestrial laser scanner RH metric values for that field shots. So, on the basis of plant functional type can I select the GEDI AGBD model for NAs and calculate field AGBD using field measured RH value?

**Comment by rupesh2** [comment]
Hi @smita2021 these models are generated using simulated GEDI waveform/LVIS. You might want to test out how these perform for metrics from TLS. The original allometries are provided in Duncanson et al. (Table S1) https://doi.org/10.1016/j.rse.2021.112845
