### ISSUE TITLE
Not listed 

### ISSUE THREAD

**Issue by shamik394** [ornldaac/gedi_tutorials#8]
This file (GEDI04_A_2019133103100_O02354_03_T00724_02_002_02_V002.h5) doesn't exist in the github page.

**Comment by rupesh2** [comment]
Hi @shamik394 , you will have first to download the file as described in step **3. Downloading the GEDI L4A files** of the tutorial: https://github.com/ornldaac/gedi_tutorials/blob/main/2_gedi_l4a_subsets.ipynb

**Comment by shamik394** [comment]
Thank you - this was very helpful.
